name: snake game
on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: NadineJackson1
          svg_out_path: dist/github-contribution-grid-snake.svg
        id: snake-gif
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          publish_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
